version: "3.8"

services:
  postgres:
    image: postgres:12.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: filings_db
    ports:
      - "5434:5432"  # Map container 5432 to host 5433 to avoid conflict if you run other DBs
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:6.20
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "15432:80"  # Access pgAdmin at http://localhost:15432
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: filings_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - .:/app
    working_dir: /app/src/web

volumes:
  pgdata:
  pgadmin-data: